// Sample report data for "View Sample Project" demo

export const sampleReportData = {
  location_summary: {
    location_name: "Cikarang Industrial Zone – Block A17",
    coordinates: "-6.3070, 107.1610",
    land_area: 2500,
    zoning_category: "Industrial",
    parcel_id: "sample-demo-12345",
  },
  engine_output: {
    risk_score: 46,
    classification: "Moderate" as "Low" | "Moderate" | "High",
    dominant_factor: "Flood Exposure",
    factor_breakdown: [
      {
        factor: "Soil Stability",
        raw_value: 62,
        weight: 0.35,
        weighted_value: 21.7,
      },
      {
        factor: "Flood Exposure",
        raw_value: 45,
        weight: 0.25,
        weighted_value: 11.25,
      },
      {
        factor: "Environmental Sensitivity",
        raw_value: 38,
        weight: 0.15,
        weighted_value: 5.7,
      },
      {
        factor: "Zoning Compliance",
        raw_value: 25,
        weight: 0.15,
        weighted_value: 3.75,
      },
      {
        factor: "Topography Index",
        raw_value: 30,
        weight: 0.10,
        weighted_value: 3.0,
      },
    ],
    model_version: "LR-Engine-v1.0",
  },
  confidence_output: {
    confidence_score: 0.85,
    completeness_score: 0.92,
    consistency_score: 0.88,
    recency_score: 0.95,
    low_integrity: false,
  },
  interpretation: {
    summary: "This parcel in Cikarang Industrial Zone shows moderate overall risk (46/100). The primary concern is flood exposure due to proximity to coastal zones and low elevation. Soil stability is optimal for industrial construction. The assessment carries high confidence (85%) based on comprehensive data coverage.",
    key_observations: [
      "Flood Exposure: Raw value 45/100 (weight: 25%) contributing 11.3% to composite score.",
      "Soil Stability: Raw value 62/100 (weight: 35%) contributing 21.7% to composite score.",
      "Environmental Sensitivity: Low risk at 38/100 with minimal seismic activity in the region.",
      "Data completeness is above 90% threshold — findings are reliable for preliminary assessment.",
    ],
    recommended_action: "Moderate risk profile driven by flood exposure. Recommend targeted investigation of flood mitigation infrastructure and verification of industrial zoning compliance before commitment.",
    limitations: "Interpretation generated by LandRisk Deterministic Engine (AI service unavailable). Risk indices are based on seeded hackathon data and should not be used for actual investment decisions. Confidence: 85%.",
    is_ai_generated: false,
  },
  metadata: {
    data_source: "BPN Geospatial 2024",
    last_updated: new Date().toISOString(),
  },
};
