import { PrismaClient } from "@prisma/client";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

// Indonesian parcel data for hackathon demo
const PARCELS = [
  {
    location_name: "Cikarang Industrial Zone – Block A17",
    latitude: -6.307,
    longitude: 107.161,
    land_area: 2500,
    zoning_category: "Industrial",
    soil_index: 62,
    flood_index: 45,
    environmental_index: 38,
    zoning_index: 25,
    topography_index: 30,
    data_completeness: 0.92,
    model_consistency: 0.88,
    data_recency: 0.95,
    data_source_label: "BPN Geospatial 2024",
  },
  {
    location_name: "Tangerang Selatan – BSD City Lot 5",
    latitude: -6.3,
    longitude: 106.652,
    land_area: 1800,
    zoning_category: "Mixed-Use",
    soil_index: 35,
    flood_index: 55,
    environmental_index: 42,
    zoning_index: 30,
    topography_index: 25,
    data_completeness: 0.85,
    model_consistency: 0.9,
    data_recency: 0.88,
    data_source_label: "BPN Geospatial 2024",
  },
  {
    location_name: "Jakarta Selatan – Kemang Raya",
    latitude: -6.26,
    longitude: 106.814,
    land_area: 950,
    zoning_category: "Commercial",
    soil_index: 48,
    flood_index: 72,
    environmental_index: 55,
    zoning_index: 35,
    topography_index: 20,
    data_completeness: 0.95,
    model_consistency: 0.92,
    data_recency: 0.97,
    data_source_label: "DKI Jakarta Open Data",
  },
  {
    location_name: "Bandung – Dago Atas Hilltop",
    latitude: -6.863,
    longitude: 107.618,
    land_area: 3200,
    zoning_category: "Residential",
    soil_index: 28,
    flood_index: 15,
    environmental_index: 65,
    zoning_index: 20,
    topography_index: 72,
    data_completeness: 0.78,
    model_consistency: 0.85,
    data_recency: 0.82,
    data_source_label: "Bandung Geoportal",
  },
  {
    location_name: "Surabaya – Tanjung Perak Port Area",
    latitude: -7.224,
    longitude: 112.733,
    land_area: 5000,
    zoning_category: "Industrial",
    soil_index: 55,
    flood_index: 78,
    environmental_index: 60,
    zoning_index: 40,
    topography_index: 15,
    data_completeness: 0.88,
    model_consistency: 0.82,
    data_recency: 0.9,
    data_source_label: "Surabaya GIS Portal",
  },
  {
    location_name: "Semarang – Genuk Industrial Park",
    latitude: -6.966,
    longitude: 110.459,
    land_area: 4200,
    zoning_category: "Industrial",
    soil_index: 70,
    flood_index: 82,
    environmental_index: 48,
    zoning_index: 30,
    topography_index: 22,
    data_completeness: 0.8,
    model_consistency: 0.78,
    data_recency: 0.85,
    data_source_label: "BPN Jawa Tengah",
  },
  {
    location_name: "Yogyakarta – Condongcatur Tech Park",
    latitude: -7.767,
    longitude: 110.392,
    land_area: 1500,
    zoning_category: "Mixed-Use",
    soil_index: 32,
    flood_index: 28,
    environmental_index: 35,
    zoning_index: 22,
    topography_index: 30,
    data_completeness: 0.9,
    model_consistency: 0.92,
    data_recency: 0.94,
    data_source_label: "DIY Geoportal",
  },
  {
    location_name: "Bali – Jimbaran Bay Coastal",
    latitude: -8.79,
    longitude: 115.161,
    land_area: 2800,
    zoning_category: "Tourism",
    soil_index: 42,
    flood_index: 35,
    environmental_index: 75,
    zoning_index: 50,
    topography_index: 38,
    data_completeness: 0.72,
    model_consistency: 0.8,
    data_recency: 0.75,
    data_source_label: "Bali Spatial Plan",
  },
  {
    location_name: "Makassar – Tallo River Basin",
    latitude: -5.131,
    longitude: 119.422,
    land_area: 6000,
    zoning_category: "Residential",
    soil_index: 58,
    flood_index: 85,
    environmental_index: 62,
    zoning_index: 45,
    topography_index: 18,
    data_completeness: 0.65,
    model_consistency: 0.7,
    data_recency: 0.68,
    data_source_label: "Makassar Open GIS",
  },
  {
    location_name: "Medan – KIM Industrial Zone",
    latitude: 3.569,
    longitude: 98.697,
    land_area: 3800,
    zoning_category: "Industrial",
    soil_index: 45,
    flood_index: 60,
    environmental_index: 40,
    zoning_index: 28,
    topography_index: 25,
    data_completeness: 0.7,
    model_consistency: 0.75,
    data_recency: 0.72,
    data_source_label: "Sumut Geoportal",
  },
  {
    location_name: "Bekasi – Jababeka Phase V",
    latitude: -6.28,
    longitude: 107.16,
    land_area: 2200,
    zoning_category: "Industrial",
    soil_index: 55,
    flood_index: 42,
    environmental_index: 35,
    zoning_index: 22,
    topography_index: 28,
    data_completeness: 0.93,
    model_consistency: 0.91,
    data_recency: 0.96,
    data_source_label: "BPN Geospatial 2024",
  },
  {
    location_name: "Bogor – Sentul City Highlands",
    latitude: -6.603,
    longitude: 106.851,
    land_area: 4500,
    zoning_category: "Residential",
    soil_index: 30,
    flood_index: 20,
    environmental_index: 58,
    zoning_index: 35,
    topography_index: 65,
    data_completeness: 0.82,
    model_consistency: 0.88,
    data_recency: 0.84,
    data_source_label: "Bogor GIS",
  },
  {
    location_name: "Depok – Margonda Corridor",
    latitude: -6.389,
    longitude: 106.831,
    land_area: 800,
    zoning_category: "Commercial",
    soil_index: 40,
    flood_index: 50,
    environmental_index: 30,
    zoning_index: 25,
    topography_index: 20,
    data_completeness: 0.88,
    model_consistency: 0.86,
    data_recency: 0.92,
    data_source_label: "Depok Smart City",
  },
  {
    location_name: "Palembang – Jakabaring Lakeside",
    latitude: -3.023,
    longitude: 104.789,
    land_area: 3500,
    zoning_category: "Mixed-Use",
    soil_index: 65,
    flood_index: 70,
    environmental_index: 55,
    zoning_index: 38,
    topography_index: 12,
    data_completeness: 0.58,
    model_consistency: 0.62,
    data_recency: 0.6,
    data_source_label: "Palembang Geoportal",
  },
  {
    location_name: "Balikpapan – Kariangau Industrial",
    latitude: -1.233,
    longitude: 116.831,
    land_area: 7500,
    zoning_category: "Industrial",
    soil_index: 38,
    flood_index: 25,
    environmental_index: 72,
    zoning_index: 30,
    topography_index: 45,
    data_completeness: 0.75,
    model_consistency: 0.72,
    data_recency: 0.7,
    data_source_label: "Kaltim Open Data",
  },
  {
    location_name: "Manado – Bitung Port Expansion",
    latitude: 1.441,
    longitude: 125.025,
    land_area: 4000,
    zoning_category: "Industrial",
    soil_index: 50,
    flood_index: 40,
    environmental_index: 68,
    zoning_index: 42,
    topography_index: 55,
    data_completeness: 0.55,
    model_consistency: 0.6,
    data_recency: 0.52,
    data_source_label: "Sulut Geoportal",
  },
  {
    location_name: "Malang – Batu Highland Resort",
    latitude: -7.87,
    longitude: 112.533,
    land_area: 2000,
    zoning_category: "Tourism",
    soil_index: 25,
    flood_index: 18,
    environmental_index: 70,
    zoning_index: 45,
    topography_index: 78,
    data_completeness: 0.8,
    model_consistency: 0.85,
    data_recency: 0.78,
    data_source_label: "Malang GIS",
  },
  {
    location_name: "Lombok – Mandalika SEZ",
    latitude: -8.895,
    longitude: 116.323,
    land_area: 5500,
    zoning_category: "Tourism",
    soil_index: 35,
    flood_index: 30,
    environmental_index: 80,
    zoning_index: 55,
    topography_index: 42,
    data_completeness: 0.68,
    model_consistency: 0.72,
    data_recency: 0.65,
    data_source_label: "NTB Geoportal",
  },
  {
    location_name: "Jakarta Utara – PIK 2 Reclamation",
    latitude: -6.099,
    longitude: 106.732,
    land_area: 10000,
    zoning_category: "Mixed-Use",
    soil_index: 75,
    flood_index: 88,
    environmental_index: 82,
    zoning_index: 60,
    topography_index: 10,
    data_completeness: 0.95,
    model_consistency: 0.9,
    data_recency: 0.98,
    data_source_label: "DKI Jakarta Open Data",
  },
  {
    location_name: "Tangerang – Eco Industrial City",
    latitude: -6.17,
    longitude: 106.63,
    land_area: 3000,
    zoning_category: "Industrial",
    soil_index: 42,
    flood_index: 48,
    environmental_index: 38,
    zoning_index: 25,
    topography_index: 22,
    data_completeness: 0.9,
    model_consistency: 0.88,
    data_recency: 0.92,
    data_source_label: "Tangerang Smart City",
  },
  {
    location_name: "Pontianak – Riverside Commercial",
    latitude: -0.02,
    longitude: 109.342,
    land_area: 1200,
    zoning_category: "Commercial",
    soil_index: 60,
    flood_index: 75,
    environmental_index: 50,
    zoning_index: 35,
    topography_index: 8,
    data_completeness: 0.5,
    model_consistency: 0.55,
    data_recency: 0.48,
    data_source_label: "Kalbar Open Data",
  },
  {
    location_name: "Kupang – Bolok Port Zone",
    latitude: -10.152,
    longitude: 123.585,
    land_area: 2800,
    zoning_category: "Industrial",
    soil_index: 55,
    flood_index: 22,
    environmental_index: 45,
    zoning_index: 35,
    topography_index: 40,
    data_completeness: 0.45,
    model_consistency: 0.5,
    data_recency: 0.42,
    data_source_label: "NTT Geoportal",
  },
  {
    location_name: "Jayapura – Holtekamp Business Park",
    latitude: -2.57,
    longitude: 140.722,
    land_area: 4500,
    zoning_category: "Mixed-Use",
    soil_index: 48,
    flood_index: 35,
    environmental_index: 85,
    zoning_index: 50,
    topography_index: 60,
    data_completeness: 0.4,
    model_consistency: 0.45,
    data_recency: 0.38,
    data_source_label: "Papua Open GIS",
  },
  {
    location_name: "Batam – Nongsa Digital Park",
    latitude: 1.113,
    longitude: 104.085,
    land_area: 2000,
    zoning_category: "Commercial",
    soil_index: 30,
    flood_index: 28,
    environmental_index: 40,
    zoning_index: 20,
    topography_index: 25,
    data_completeness: 0.92,
    model_consistency: 0.95,
    data_recency: 0.93,
    data_source_label: "BP Batam GIS",
  },
  {
    location_name: "Cirebon – Plered Ceramics District",
    latitude: -6.715,
    longitude: 108.557,
    land_area: 1800,
    zoning_category: "Industrial",
    soil_index: 45,
    flood_index: 38,
    environmental_index: 42,
    zoning_index: 28,
    topography_index: 32,
    data_completeness: 0.72,
    model_consistency: 0.78,
    data_recency: 0.7,
    data_source_label: "Jabar Geoportal",
  },
  {
    location_name: "Solo – Karanganyar Agri-Industrial",
    latitude: -7.589,
    longitude: 110.85,
    land_area: 5200,
    zoning_category: "Industrial",
    soil_index: 35,
    flood_index: 32,
    environmental_index: 50,
    zoning_index: 25,
    topography_index: 35,
    data_completeness: 0.85,
    model_consistency: 0.88,
    data_recency: 0.83,
    data_source_label: "Jateng Open Data",
  },
  {
    location_name: "Samarinda – Loa Janan Mining Rehab",
    latitude: -0.533,
    longitude: 117.051,
    land_area: 8000,
    zoning_category: "Industrial",
    soil_index: 72,
    flood_index: 45,
    environmental_index: 90,
    zoning_index: 65,
    topography_index: 55,
    data_completeness: 0.62,
    model_consistency: 0.58,
    data_recency: 0.55,
    data_source_label: "Kaltim Open Data",
  },
  {
    location_name: "Pekanbaru – Tenayan Raya New Town",
    latitude: 0.558,
    longitude: 101.448,
    land_area: 6500,
    zoning_category: "Residential",
    soil_index: 50,
    flood_index: 55,
    environmental_index: 65,
    zoning_index: 40,
    topography_index: 18,
    data_completeness: 0.68,
    model_consistency: 0.72,
    data_recency: 0.65,
    data_source_label: "Riau Geoportal",
  },
  {
    location_name: "Banjarmasin – Alalak Riverside",
    latitude: -3.31,
    longitude: 114.59,
    land_area: 1500,
    zoning_category: "Residential",
    soil_index: 65,
    flood_index: 80,
    environmental_index: 55,
    zoning_index: 38,
    topography_index: 10,
    data_completeness: 0.55,
    model_consistency: 0.6,
    data_recency: 0.5,
    data_source_label: "Kalsel Open GIS",
  },
  {
    location_name: "Padang – Bungus Bay Coastal",
    latitude: -1.04,
    longitude: 100.394,
    land_area: 3200,
    zoning_category: "Tourism",
    soil_index: 40,
    flood_index: 45,
    environmental_index: 70,
    zoning_index: 48,
    topography_index: 52,
    data_completeness: 0.6,
    model_consistency: 0.65,
    data_recency: 0.58,
    data_source_label: "Sumbar Geoportal",
  },
  {
    location_name: "Denpasar – Sanur Tech Hub",
    latitude: -8.694,
    longitude: 115.263,
    land_area: 900,
    zoning_category: "Commercial",
    soil_index: 28,
    flood_index: 30,
    environmental_index: 55,
    zoning_index: 40,
    topography_index: 15,
    data_completeness: 0.88,
    model_consistency: 0.9,
    data_recency: 0.85,
    data_source_label: "Bali Spatial Plan",
  },
  {
    location_name: "Jakarta Barat – Cengkareng Logistics",
    latitude: -6.142,
    longitude: 106.686,
    land_area: 7000,
    zoning_category: "Industrial",
    soil_index: 52,
    flood_index: 65,
    environmental_index: 45,
    zoning_index: 30,
    topography_index: 12,
    data_completeness: 0.94,
    model_consistency: 0.92,
    data_recency: 0.96,
    data_source_label: "DKI Jakarta Open Data",
  },
  {
    location_name: "Karawang – KIIC Industrial Phase III",
    latitude: -6.389,
    longitude: 107.292,
    land_area: 3500,
    zoning_category: "Industrial",
    soil_index: 58,
    flood_index: 52,
    environmental_index: 40,
    zoning_index: 22,
    topography_index: 20,
    data_completeness: 0.91,
    model_consistency: 0.89,
    data_recency: 0.93,
    data_source_label: "BPN Geospatial 2024",
  },
  {
    location_name: "Semarang – Marina District",
    latitude: -6.964,
    longitude: 110.398,
    land_area: 2200,
    zoning_category: "Residential",
    soil_index: 55,
    flood_index: 72,
    environmental_index: 40,
    zoning_index: 30,
    topography_index: 15,
    data_completeness: 0.82,
    model_consistency: 0.8,
    data_recency: 0.78,
    data_source_label: "BPN Jawa Tengah",
  },
  {
    location_name: "Surabaya – Citraland CBD",
    latitude: -7.311,
    longitude: 112.658,
    land_area: 1600,
    zoning_category: "Commercial",
    soil_index: 38,
    flood_index: 35,
    environmental_index: 30,
    zoning_index: 18,
    topography_index: 22,
    data_completeness: 0.9,
    model_consistency: 0.92,
    data_recency: 0.94,
    data_source_label: "Surabaya GIS Portal",
  },
  {
    location_name: "Jakarta Timur – Pulo Gadung LIK",
    latitude: -6.205,
    longitude: 106.89,
    land_area: 4000,
    zoning_category: "Industrial",
    soil_index: 48,
    flood_index: 58,
    environmental_index: 50,
    zoning_index: 32,
    topography_index: 15,
    data_completeness: 0.92,
    model_consistency: 0.88,
    data_recency: 0.94,
    data_source_label: "DKI Jakarta Open Data",
  },
  {
    location_name: "Purwakarta – KITIC Green Industrial",
    latitude: -6.558,
    longitude: 107.428,
    land_area: 5500,
    zoning_category: "Industrial",
    soil_index: 40,
    flood_index: 35,
    environmental_index: 45,
    zoning_index: 22,
    topography_index: 38,
    data_completeness: 0.85,
    model_consistency: 0.88,
    data_recency: 0.82,
    data_source_label: "Jabar Geoportal",
  },
  {
    location_name: "Sleman – Kaliurang Tech Village",
    latitude: -7.616,
    longitude: 110.414,
    land_area: 1200,
    zoning_category: "Mixed-Use",
    soil_index: 25,
    flood_index: 15,
    environmental_index: 60,
    zoning_index: 30,
    topography_index: 70,
    data_completeness: 0.78,
    model_consistency: 0.82,
    data_recency: 0.8,
    data_source_label: "DIY Geoportal",
  },
  {
    location_name: "Cilegon – Krakatau Steel Expansion",
    latitude: -6.005,
    longitude: 106.044,
    land_area: 9000,
    zoning_category: "Industrial",
    soil_index: 60,
    flood_index: 50,
    environmental_index: 68,
    zoning_index: 45,
    topography_index: 20,
    data_completeness: 0.78,
    model_consistency: 0.75,
    data_recency: 0.72,
    data_source_label: "Banten Geoportal",
  },
  {
    location_name: "Nusantara IKN – Capital Core Zone",
    latitude: -1.156,
    longitude: 116.839,
    land_area: 15000,
    zoning_category: "Government",
    soil_index: 42,
    flood_index: 30,
    environmental_index: 88,
    zoning_index: 15,
    topography_index: 48,
    data_completeness: 0.7,
    model_consistency: 0.65,
    data_recency: 0.95,
    data_source_label: "IKN Authority GIS",
  },
  {
    location_name: "Sidoarjo – Porong Recovery Zone",
    latitude: -7.468,
    longitude: 112.719,
    land_area: 3800,
    zoning_category: "Industrial",
    soil_index: 88,
    flood_index: 75,
    environmental_index: 72,
    zoning_index: 55,
    topography_index: 12,
    data_completeness: 0.92,
    model_consistency: 0.88,
    data_recency: 0.9,
    data_source_label: "Jatim Open Data",
  },
  {
    location_name: "Jakarta Pusat – Sudirman CBD Core",
    latitude: -6.21,
    longitude: 106.823,
    land_area: 500,
    zoning_category: "Commercial",
    soil_index: 30,
    flood_index: 45,
    environmental_index: 25,
    zoning_index: 15,
    topography_index: 10,
    data_completeness: 0.98,
    model_consistency: 0.96,
    data_recency: 0.99,
    data_source_label: "DKI Jakarta Open Data",
  },
  {
    location_name: "Lampung – Bakauheni Toll Gateway",
    latitude: -5.872,
    longitude: 105.757,
    land_area: 6000,
    zoning_category: "Mixed-Use",
    soil_index: 52,
    flood_index: 40,
    environmental_index: 55,
    zoning_index: 35,
    topography_index: 30,
    data_completeness: 0.62,
    model_consistency: 0.68,
    data_recency: 0.6,
    data_source_label: "Lampung Geoportal",
  },
  {
    location_name: "Bandung – Gedebage Tech Valley",
    latitude: -6.946,
    longitude: 107.697,
    land_area: 2800,
    zoning_category: "Mixed-Use",
    soil_index: 35,
    flood_index: 42,
    environmental_index: 48,
    zoning_index: 25,
    topography_index: 35,
    data_completeness: 0.86,
    model_consistency: 0.88,
    data_recency: 0.84,
    data_source_label: "Bandung Geoportal",
  },
  {
    location_name: "Gresik – Maspion Industrial",
    latitude: -7.156,
    longitude: 112.655,
    land_area: 4500,
    zoning_category: "Industrial",
    soil_index: 50,
    flood_index: 45,
    environmental_index: 52,
    zoning_index: 28,
    topography_index: 18,
    data_completeness: 0.84,
    model_consistency: 0.82,
    data_recency: 0.86,
    data_source_label: "Jatim Open Data",
  },
  {
    location_name: "Labuan Bajo – Komodo Gateway",
    latitude: -8.495,
    longitude: 119.88,
    land_area: 2000,
    zoning_category: "Tourism",
    soil_index: 38,
    flood_index: 25,
    environmental_index: 92,
    zoning_index: 60,
    topography_index: 58,
    data_completeness: 0.52,
    model_consistency: 0.55,
    data_recency: 0.48,
    data_source_label: "NTT Geoportal",
  },
  {
    location_name: "Ambon – Passo New Town",
    latitude: -3.652,
    longitude: 128.232,
    land_area: 3500,
    zoning_category: "Residential",
    soil_index: 45,
    flood_index: 35,
    environmental_index: 65,
    zoning_index: 40,
    topography_index: 62,
    data_completeness: 0.42,
    model_consistency: 0.48,
    data_recency: 0.4,
    data_source_label: "Maluku Open GIS",
  },
  {
    location_name: "Sorong – New Port Industrial",
    latitude: -0.884,
    longitude: 131.249,
    land_area: 5000,
    zoning_category: "Industrial",
    soil_index: 52,
    flood_index: 38,
    environmental_index: 78,
    zoning_index: 48,
    topography_index: 42,
    data_completeness: 0.38,
    model_consistency: 0.42,
    data_recency: 0.35,
    data_source_label: "Papua Barat GIS",
  },
  {
    location_name: "Tegal – North Coast Aquaculture",
    latitude: -6.869,
    longitude: 109.14,
    land_area: 4200,
    zoning_category: "Agriculture",
    soil_index: 55,
    flood_index: 68,
    environmental_index: 58,
    zoning_index: 42,
    topography_index: 8,
    data_completeness: 0.7,
    model_consistency: 0.72,
    data_recency: 0.68,
    data_source_label: "Jateng Open Data",
  },
  {
    location_name: "Serang – Banten Lama Heritage",
    latitude: -6.118,
    longitude: 106.163,
    land_area: 1500,
    zoning_category: "Tourism",
    soil_index: 42,
    flood_index: 50,
    environmental_index: 60,
    zoning_index: 55,
    topography_index: 25,
    data_completeness: 0.65,
    model_consistency: 0.7,
    data_recency: 0.62,
    data_source_label: "Banten Geoportal",
  },
];

async function main() {
  console.log("🌱 Seeding database with Indonesian land parcels...");

  for (const data of PARCELS) {
    await prisma.parcel.create({
      data: {
        ...data,
        last_updated: new Date(
          Date.now() - Math.floor(Math.random() * 90) * 24 * 60 * 60 * 1000,
        ),
      },
    });
  }

  console.log(`✅ Seeded ${PARCELS.length} parcels successfully.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
